#!/bin/bash
mkdir -p ./dist
echo "" | ./get/index.sh "" "/" > ./dist/index.html

mkdir -p ./dist/static
shopt -s globstar
for pathname in static/**
do
    if [[ -f "$pathname" ]]
    then
        ./utils/static/copy.sh "$pathname"
    fi
done

mkdir -p ./dist/blog
mkdir -p ./dist/nolayout/blog
DATA=`./get/html-assets/blog/html.sh`
echo "$DATA" | ./get/index.sh "`./get/html-assets/blog/title.sh`" "/blog" > ./dist/blog/index.html
echo "$DATA" > ./dist/nolayout/blog/index.html

mkdir -p ./dist/contact
mkdir -p ./dist/nolayout/contact
DATA=`./get/html-assets/contact/html.sh` 
echo "$DATA" | ./get/index.sh "`./get/html-assets/contact/title.sh`" "/contact" > ./dist/contact/index.html
echo "$DATA" > ./dist/nolayout/contact/index.html

mkdir -p ./dist/about
mkdir -p ./dist/nolayout/about
DATA=`./get/html-assets/about/html.sh`
echo "$DATA" | ./get/index.sh "`./get/html-assets/about/title.sh`" "/about" > ./dist/about/index.html
echo "$DATA" > ./dist/nolayout/about/index.html

mkdir -p ./dist/projects
mkdir -p ./dist/nolayout/projects
DATA=`./get/html-assets/projects/html.sh`
echo "$DATA" | ./get/index.sh "`./get/html-assets/projects/title.sh`" "/projects" > ./dist/projects/index.html
echo "$DATA" > ./dist/nolayout/projects/index.html

for pathname in src/articles/**
do
    if [[ -f "$pathname" ]]
    then
        DATA=`./get/article/html.sh "$pathname"`
        BASEPATH=`./get/article/basepath.sh "$pathname"`
        ROOTPATH="./dist$BASEPATH"
        NOLAYOUTPATH="./dist/nolayout$BASEPATH"

        mkdir -p "$ROOTPATH"
        mkdir -p "$NOLAYOUTPATH"
        TITLE=`./get/article/title.sh "$pathname"`

        echo "$DATA" | ./get/index.sh "$TITLE" "$BASEPATH/index.html" > $ROOTPATH/index.html
        echo "$DATA" > $NOLAYOUTPATH/index.html
    fi
done

# Minification...
if [[ "$MODE" =~ "prod" ]] || [[ "$1" =~ "prod" ]]
then
    for pathname in dist/**
    do
        if [[ -f "$pathname" ]]
        then
            EXT=${pathname##*.}
            if [[ "$EXT" == "js" ]]
            then
                echo "Minifying $pathname"
                MIN=`./utils/minify/js.sh "$pathname"`
                echo "$MIN" > "$pathname"
            elif [[ "$EXT" == "css" ]]
            then
                echo "Minifying $pathname"
                MIN=`./utils/minify/css.sh "$pathname"`
                echo "$MIN" > "$pathname"
            elif [[ "$EXT" == "html" ]]
            then
                echo "Minifying $pathname"
                MIN=`./utils/minify/html.sh "$pathname"`
                echo "$MIN" > "$pathname"
            fi
        fi
    done
fi
